import { readFile, writeFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const read = f => readFile(new URL(f, root), 'utf8');
const controller = (await read('src/controller.js')).replace('export class ', 'class ');
const host = (await read('src/host-client.js')).replace('__CONTROLLER__', () => controller).replace('window.__ModuleLoader__.load(', 'captureHost(');
const business = (await read('src/business-client.js')).replace('window.__ModuleLoader__.load(', 'captureBusiness(');
await writeFile(new URL('client.js', root), `// Generated by scripts/build.mjs; source files are in src/.\nwindow.__ModuleLoader__.load({id:'dsh-huaxue-workbench',factory(require){\nlet hostDef,businessDef;const captureHost=d=>hostDef=d,captureBusiness=d=>businessDef=d;\n${host}\n${business}\nconst host=hostDef.factory(require),business=businessDef.factory(require);return {inject:host.inject,apply(ctx){host.apply(ctx);business.apply(ctx);}};\n}});\n`);
console.log('Built standalone client');
